import Head from 'next/head'
import CardWithText from '../components/common/card/TopicCard'
import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My dev journey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="w-full flex flex-wrap">
          <CardWithText text="HTML" size='w-1/6' boxColor="blue"/>
        </div>
      </Layout>
    </div>
  )
}
