import Head from 'next/head'
import CardWithText from '../components/common/card/TopicCard'
import { topics } from '../components/constant/topics'
import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My dev journey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <p className="text-14 my-5">Share all the knowledge i have accumulated</p>
        <div className="w-full flex flex-wrap gap-10">
          {topics && topics.map((item,key)=>{
            return <CardWithText size="w-1/6" img={item.img} introText={item.introText} link={item.link} />
          })}
          
        </div>
      </Layout>
    </div>
  )
}
