import Head from 'next/head'
import TextShower from '../components/common/TextShower'
import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My dev journey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="w-full">
          <TextShower text="Coding somehow is best choice for every body.........." />
        </div>
      </Layout>
    </div>
  )
}
